version: "3"

volumes:
  u-vol:
    name: "urcraze-vol"
  PSQL-vol:
    name: "db-vol"
  PG-vol:

services:
  #? Application data
  # next-app:
  #   container_name: "ecommerce-app"
  #   build: ./
  #   volumes:
  #     - u-vol:/app/ur-craze
  #     - ./:/app/ur-craze
  #     - ./app:/app/ur-craze
  #   env_file:
  #     - .env
  #   expose:
  #     - "${PORT}"
  #   stdin_open: true
  #   ports:
  #     - "${PORT}:${PORT}"
  #   depends_on:
  #     - pg_admin
  #     - database

  #? Database of e-commerce site which postgres
  database:
    image: "postgres:alpine"
    ports:
      - "${PSQL_PORT}:${PSQL_PORT}"
    expose:
      - "${PSQL_PORT}"
    stdin_open: true
    restart: "always"
    volumes:
      - PSQL-vol:/postgres/data
      - PSQL-vol:/var/lib/postgresql/data
    #! Main Content
    environment:
      POSTGRES_DATABASE: ${PSQL_MAIN_DB}
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PWD}
    env_file:
      - .env
    depends_on:
      - pg_admin

  #? PG admin page
  pg_admin:
    image: "dpage/pgadmin4"
    volumes:
      - PG-vol:/var/lib/pgadmin
    ports:
      - "${PG_PORT}:80"
    expose:
      - "${PG_PORT}"
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PWD}
    restart: "always"
    stdin_open: true
